title: My blog
description: My very nice blog
author: "Jorge Sanz"

theme: minima

base_url: /gh-pages-minima-starter



# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - LICENSE
    - README.md
